AllCops:
  NewCops: enable
  Exclude:
    - db/migrate/**/*
    - db/schema.rb
    - config/**/*
    - script/**/*
    - bin/**/*
    - test/**/*
    - app/admin/**/*
    - app/channels/**/*
    - app/jobs/**/*
    - node_modules/**/*
    - Gemfile
    - Rakefile
    - config.ru

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 2