databases:
  - name: vitebsk-site_production
    databaseName: vitebsk-site_production
    user: sk8higher

services:
  - type: web
    name: mysite
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vitebsk-site_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
