default: &default
  adapter: postgresql
  username: sk8higher
  password: somepass
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vitebsk-site_development

test:
  <<: *default
  adapter: sqlite3
  pool: 50
  timeout: 100000
  database: db/test.sqlite3

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: vitebsk-site_production
