name: Run tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.2'

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "16.x"

    - name: Install openssl
      run: |
        sudo apt-get update -yq
        sudo apt-get install -y openssl

    - name: Install dependencies
      run: |
        gem install bundler --no-document
        bundle install --jobs 4 --retry 3
        sudo apt-get update && sudo apt-get install yarn
      
    - name: Set up database
      run: |
        bundle exec rails db:create db:migrate RAILS_ENV=test
        
    - name: Run tests
      env:
        RAILS_ENV: test
      run: |
        bin/rails assets:precompile
        bundle exec rspec spec/

    - name: Publish to coveralls.io
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ github.token }}
