name: Run tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.2'

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "16.x"

    - name: Install dependencies
      run: |
        gem install bundler --no-document
        bundle install --jobs 4 --retry 3
      
    - name: Set up database
      run: |
        bundle exec rails db:create db:migrate RAILS_ENV=test
        
    - name: Run tests
      run: |
        bundle exec rspec spec/
